In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

import joblib

pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_csv(r"C:\Users\workk\OneDrive\Desktop\Mental Health Risk Prediction\Student Depression Dataset.csv")

In [3]:
for col in df.columns:
    print(col)

id
Gender
Age
City
Profession
Academic Pressure
Work Pressure
CGPA
Study Satisfaction
Job Satisfaction
Sleep Duration
Dietary Habits
Degree
Have you ever had suicidal thoughts ?
Work/Study Hours
Financial Stress
Family History of Mental Illness
Depression

In [4]:
selected_columns = [

    'Gender',

    'Age',

    'Academic Pressure',

    'CGPA',

    'Study Satisfaction',

    'Sleep Duration',

    'Dietary Habits',

    'Have you ever had suicidal thoughts ?',

    'Work/Study Hours',

    'Financial Stress',

    'Family History of Mental Illness',

    'Depression'
]

In [5]:
df = df[selected_columns]

In [6]:
df.shape

(27901, 12)

In [7]:
df.columns = [

    'gender',

    'age',

    'academic_pressure',

    'cgpa',

    'study_satisfaction',

    'sleep_duration',

    'dietary_habits',

    'suicidal_thoughts',

    'work_study_hours',

    'financial_stress',

    'family_history',

    'depression'
]

In [8]:
df.head()

,gender,age,academic_pressure,cgpa,study_satisfaction,sleep_duration,dietary_habits,suicidal_thoughts,work_study_hours,financial_stress,family_history,depression
0,Male,33.0,5.0,8.97,2.0,5-6 hours,Healthy,Yes,3.0,1.0,No,1
1,Female,24.0,2.0,5.90,5.0,5-6 hours,Moderate,No,3.0,2.0,Yes,0
2,Male,31.0,3.0,7.03,5.0,Less than 5 hours,Healthy,No,9.0,1.0,Yes,0
3,Female,28.0,3.0,5.59,2.0,7-8 hours,Moderate,Yes,4.0,5.0,Yes,1
4,Female,25.0,4.0,8.13,3.0,5-6 hours,Moderate,Yes,1.0,1.0,No,0

In [9]:
for col in df.columns:

    print(f"\nColumn: {col}")

    print(df[col].unique())

Column: gender
['Male' 'Female']

Column: age
[33. 24. 31. 28. 25. 29. 30. 27. 19. 20. 23. 18. 21. 22. 34. 32. 26. 39.
 35. 42. 36. 58. 49. 38. 51. 44. 43. 46. 59. 54. 48. 56. 37. 41.]

Column: academic_pressure
[5. 2. 3. 4. 1. 0.]

Column: cgpa
[ 8.97    5.9     7.03    5.59    8.13    5.7     9.54    8.04    9.79
  8.38    6.1     7.04    8.52    5.64    8.58    6.51    7.25    7.83
  9.93    8.74    6.73    5.57    8.59    7.1     6.08    5.74    9.86
  6.7     6.21    5.87    6.37    9.72    5.88    9.56    6.99    5.24
  9.21    7.85    6.95    5.86    7.92    9.66    8.94    9.71    7.87
  5.6     7.9     5.46    6.79    8.7     7.38    8.5     7.09    9.82
  8.89    7.94    9.11    6.75    7.53    9.49    9.01    7.64    5.27
  6.      9.44    5.75    7.51    9.05    6.38    8.95    9.88    5.32
  6.27    7.7     8.1     9.59    8.96    5.51    7.43    8.79    9.95
  5.37    6.86    8.32    9.74    5.66    7.48    8.23    8.81    6.03
  5.56    5.68    5.14    7.61    6.17    8.17    9.87    8.75    6.16
  9.5     7.99    5.67    8.92    6.19    5.76    6.25    5.11    5.58
  5.65    9.89    8.03    6.61    9.41    8.64    7.21    8.28    6.04
  9.13    8.08    9.96    5.12    8.35    7.07    9.6     9.24    8.54
  8.78    8.93    8.91    9.04    6.83    5.85    7.74    6.41    8.9
  7.75    7.88    5.42    7.52    7.68    8.4     9.39    6.84    5.99
  8.62    8.53    7.47    6.78    6.42    9.92    8.39    5.89    7.22
  6.81    9.02    9.97    9.63    9.67    5.41    7.27    6.05    6.85
  9.33    5.81    6.53    5.98    6.02    6.74    5.26    7.72    7.39
  8.43    9.34    5.44    5.82    5.72    8.19    8.44    8.98    9.37
  5.8     7.28    7.6     7.91    9.17    7.46    9.43    9.91    9.36
  5.16    7.08    9.26    8.83   10.      7.8     9.46    6.63    7.24
  6.47    7.77    5.06    7.17    8.24    6.88    9.03    5.08    5.45
  8.46    9.19    6.36    8.73    7.11    9.12    9.4     8.11    9.98
  5.55    8.61    8.14    6.89    9.84    5.48    8.21    7.82    8.55
  5.79    8.77    8.29    6.92    7.37    9.7     6.26    7.26    7.5
  6.82    7.15    5.77    5.91    5.1     7.71    9.06    5.71    5.84
  9.42    6.23    6.29    5.25    9.69    9.9     6.39    8.09    5.83
  5.47    6.56    8.71    9.94    6.69    5.52    7.3     7.02    6.33
  8.07    8.37    8.      7.79    8.65    6.28    7.35    8.69    7.12
  7.32    7.13    5.97    5.09    6.91    6.76    6.52    7.45    8.56
  6.5     8.63    8.27    8.49    6.59    9.29    5.3     7.06    5.38
  6.65    9.16    8.01    8.25    8.02    8.47    7.34    8.88    7.14
  8.42    5.17    9.1     7.49    9.85    7.42    9.31    6.35    7.
  5.39    5.61    9.78    9.25    5.69    9.47    8.16    7.23    6.46
  0.      8.26    6.32    6.77    8.85    5.03    7.65    5.78    6.24
  5.35    6.06    7.78    6.64    7.0625  6.98    6.44    6.09  ]

Column: study_satisfaction
[2. 5. 3. 4. 1. 0.]

Column: sleep_duration
['5-6 hours' 'Less than 5 hours' '7-8 hours' 'More than 8 hours' 'Others']

Column: dietary_habits
['Healthy' 'Moderate' 'Unhealthy' 'Others']

Column: suicidal_thoughts
['Yes' 'No']

Column: work_study_hours
[ 3.  9.  4.  1.  0. 12.  2. 11. 10.  6.  8.  5.  7.]

Column: financial_stress
[ 1.  2.  5.  3.  4. nan]

Column: family_history
['No' 'Yes']

Column: depression
[1 0]

In [10]:
from sklearn.preprocessing import LabelEncoder

label_encoders = {}

for col in df.columns:

    if df[col].dtype == 'object':

        le = LabelEncoder()

        df[col] = le.fit_transform(df[col])

        label_encoders[col] = le

In [11]:
df.head()

,gender,age,academic_pressure,cgpa,study_satisfaction,sleep_duration,dietary_habits,suicidal_thoughts,work_study_hours,financial_stress,family_history,depression
0,1,33.0,5.0,8.97,2.0,0,0,1,3.0,1.0,0,1
1,0,24.0,2.0,5.90,5.0,0,1,0,3.0,2.0,1,0
2,1,31.0,3.0,7.03,5.0,2,0,0,9.0,1.0,1,0
3,0,28.0,3.0,5.59,2.0,1,1,1,4.0,5.0,1,1
4,0,25.0,4.0,8.13,3.0,0,1,1,1.0,1.0,0,0

In [12]:
X = df.drop('depression', axis=1)

y = df['depression']

In [13]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

In [14]:
X_scaled.shape, y.shape

((27901, 11), (27901,))

In [15]:
import joblib

joblib.dump(scaler, 'scaler.pkl')

joblib.dump(label_encoders, 'label_encoders.pkl')

['label_encoders.pkl']

In [16]:
pd.DataFrame(X_scaled).head()

,0,1,2,3,4,5,6,7,8,9,10
0,0.891416,1.463165,1.345543,0.893393,-0.693425,-1.421696,-1.182363,0.761745,-1.121213,-1.488788,-0.968421
1,-1.121811,-0.371474,-0.826104,-1.194076,1.510636,-1.421696,-0.375705,-1.312775,-1.121213,-0.793050,1.032609
2,0.891416,1.055467,-0.102222,-0.425724,1.510636,0.459582,-1.182363,-1.312775,0.497095,-1.488788,1.032609
3,-1.121811,0.443921,-0.102222,-1.404862,-0.693425,-0.481057,-0.375705,0.761745,-0.851495,1.294167,1.032609
4,-1.121811,-0.167625,0.621660,0.322229,0.041262,-1.421696,-0.375705,0.761745,-1.660650,-1.488788,-0.968421